name: Deploy to Satsuma Service

on:
    push:
        tags:
            - "*"

jobs:
    buildAndDeploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Install node
              uses: actions/setup-node@v1
              with:
                  node-version: 18
            - name: Install Yarn
              run: npm i -g yarn
            - name: Install Libs
              run: yarn --frozen-lockfile
            - name: Codegen
              run: yarn codegen
            - name: Build
              run: yarn build
            - name: Deploy to Satsuma
              run: |
                  npx graph deploy aavegotchi-gotchi-subgraph --version-label ${GITHUB_REF#refs/*/} --node https://app.satsuma.xyz/api/subgraphs/deploy --ipfs https://api.thegraph.com/ipfs/ --deploy-key ${{secrets.SATSUMA_ACCESS_TOKEN}} --product hosted-service
              shell: bash
